# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject

# 必备
    pod 'SnapKit' #布局
    pod 'Kingfisher' #图片库
    pod 'Alamofire' #网络库
    #pod 'Reachability.swift' # 替换苹果的 Reachability 类
    pod 'SwiftyJSON' #json解析库
    pod 'HandyJSON'
    pod 'Toast-Swift' #加载指示器
    pod 'PKHUD' # HUD
    pod 'SwiftPullToRefresh' #上下拉刷新
    pod 'URLNavigator' #路由跳转

# 扩展
    pod 'SwifterSwift' 
    #pod 'EZSwiftExtensions' 
    #pod 'ExSwift' 

# 响应式编程框架
    pod 'RxSwift'
    pod 'RxCocoa'

# 框架级工具
    pod 'Swinject'
    pod 'SwiftLint' # Swift 代码规范检查工具
    pod 'Aspects' # 面向切面编程（AOP）库
    #pod 'Quick' # 测试框架
    pod 'CocoaLumberjack/Swift' # 日志

pod 'DoraemonKit/Core', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']
    pod 'DoraemonKit/WithLogger', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']
    pod 'DoraemonKit/WithGPS', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']
    pod 'DoraemonKit/WithLoad', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']
    pod 'DoraemonKit/WithDatabase', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']
    pod 'DoraemonKit/WithMLeaksFinder', :git => "https://github.com/didi/DoraemonKit.git", :tag => '3.0.0', :configurations => ['Debug']


# 工具
    pod 'TextAttributes' #从attributed strings处理
    pod 'SwiftyAttributes' #富文本
    pod 'UIImageColors' #从图像中获取最主要和最突出的颜色。
    pod 'SwiftDate' #日期
    pod 'IQKeyboardManagerSwift' #键盘相关
    pod 'CryptoSwift' #加密库
    pod 'Validator' #正则判断		
    pod 'KeychainAccess' # Keychain

  target 'SwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
