# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject
    pod 'RxSwift'
    pod 'Swinject'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'HandyJSON'

  target 'SwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
