# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Swinject'
    pod 'SnapKit'
    pod 'Kingfisher' #图片库
    pod 'Alamofire' #网络库
    pod 'SwiftyJSON'
    pod 'HandyJSON'
    #pod 'Locksmith' # Keychain
    #pod 'SwiftLint' # Swift 代码规范检查工具
    #pod 'Aspects' 
    #pod 'Quick' # 测试框架
    #pod 'CocoaLumberjack/Swift' # 日志


  target 'SwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
